name: Frontend Continuous Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: CI=true npm test

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://a679c5483e1b54697ad3a5b56da7344f-734522383.us-east-1.elb.amazonaws.com -t $ECR_REGISTRY/frontend:$IMAGE_TAG ./starter/frontend
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws eks update-kubeconfig --name demo --region us-east-1
          cd starter/frontend/k8s
          kustomize edit set image frontend=$ECR_REGISTRY/frontend:$IMAGE_TAG
          kustomize build | kubectl apply -f -